In [20]:
import urllib.request as url
from bs4 import BeautifulSoup
import pandas as pd
#link="https://www.flipkart.com/search?q=samsung&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
link="https://www.flipkart.com/search?q=samsung&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=price_asc"
page=url.urlopen(link)
print(page)

<http.client.HTTPResponse object at 0x000001E35E9E93C8>

In [21]:
soup=BeautifulSoup(page,"html")

In [22]:
name=soup.find_all("div",class_="_3wU53n")
price=soup.find_all("div",class_="_1vC4OE _2rQ-NK")
rating=soup.find_all("div",class_='hGSR34')

In [23]:
na=[]
pr=[]
ra=[]

for _ in name:
    na.append(_.getText())

for _ in price:
    pr.append(_.getText())

for _ in rating:
    ra.append(_.getText())

In [24]:
t=list(zip(na,pr,ra))
df=pd.DataFrame(t)
df

                                  0       1    2
0                 Samsung Guru 1200  ₹1,100  4.3
1                 Samsung Guru 1200  ₹1,100  4.3
2                 Samsung Guru 1200  ₹1,100  4.3
3                 Samsung Guru 1200  ₹1,200  4.3
4   Samsung Guru FM Plus SM-B110E/D  ₹1,250  4.3
5              Samsung Guru FM Plus  ₹1,375  4.2
6                   Samsung Guru GT  ₹1,399  4.1
7              Samsung Guru FM Plus  ₹1,450  4.2
8              Samsung Guru Music 2  ₹1,450  4.3
9              Samsung Guru FM Plus  ₹1,499  4.2
10  Samsung Guru FM Plus SM-B110E/D  ₹1,500  4.3
11  Samsung Guru FM Plus SM-B110E/D  ₹1,500  4.3
12             Samsung Guru FM Plus  ₹1,600  4.2
13           Samsung Guru Plus B110  ₹1,700  4.1
14             Samsung Guru Music 2  ₹1,749  4.3
15    Samsung Guru Music 2 SM-B310E  ₹1,749  4.1
16             Samsung Guru Music 2  ₹1,760  4.3
17             Samsung Guru Music 2  ₹1,760  4.3
18       Samsung Metro 313 Dual Sim  ₹1,850  4.2
19       Samsung Metro 313 Dual Sim  ₹1,990  4.3
20                Samsung Metro 313  ₹1,999    4
21                Samsung Metro 313  ₹2,050    4
22                Samsung Metro 313  ₹2,120  4.1
23       Samsung Metro 313 Dual Sim  ₹2,120  4.2